# Site settings
title: Jesse
description: "Hi, 我是 Jesse，一名 iOS 开发者，热爱编程，平常也喜欢摄影。欢迎大家能多多交流。"
baseurl: ""
url: ""
# url: "http://joshgerdes.com/jekyll-uno"
# baseurl: "https://JesseZhu.com/"
#baseurl: 'http://127.0.0.1:4000/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: "Jesse Zhu"
  email: Jesse.sundy@gmail.com
  twitter_username: JesseZhuLuck
  facebook_username: JesseZhuLuck
  github_username: jessezhu
  linkedin_username: JesseZhuLuck

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
# highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  # syntax_highlighter: pygments
  # syntax_highlighter: rouge
  # syntax_highlighter_opts:
  #   line_numbers: true
  math_engine: mathjax

plugins: ["jekyll-paginate"]
exclude: ["README.md", "Gemfile", "Gemfile.lock", "screenshot.png"]
