# Site settings
title: Jesse
description: 'Hi, 我是Jesse,一名iOS开发者，热爱编程，平常也喜欢摄影，听音乐,看电影，欢迎大家能多多交流。'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: 'http://JesseZhu.com/'
#baseurl: 'http://127.0.0.1:4000/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Jesse Zhu'
  email: Jesse.sundy@gmail.com
  twitter_username: JesseZhuLuck
  facebook_username: JesseZhuLuck
  github_username:  jessezhu
  linkedin_username:  JesseZhuLuck

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
# highlighter: rouge
highlighter: pygments

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false
  syntax_highlighter: pygments
  math_engine: mathjax

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
